# Generated by Django 5.0.6 on 2024-06-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_userlike_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postsaved',
            field=models.BooleanField(default=False),
        ),
    ]
