# Generated by Django 5.0.6 on 2024-06-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_save'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='save',
            unique_together=set(),
        ),
    ]
