# Generated by Django 5.0.6 on 2024-06-25 10:07

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_save_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(default='default.jpg', upload_to=post.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
