# Generated by Django 5.0.6 on 2024-06-25 11:37

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_picture_remove_post_postsaved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.FileField(default='default.jpg', upload_to=post.models.user_directory_path, verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='post',
            name='postsaved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='userlike',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PostFileContent',
        ),
    ]
