# Generated by Django 5.0.6 on 2024-07-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_catagory_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
